//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produits()
        {
            this.Fournit = new HashSet<Fournit>();
            this.Livrer = new HashSet<Livrer>();
            this.Sont_present = new HashSet<Sont_present>();
            this.Rubrique = new HashSet<Rubrique>();
        }
    
        public int produit_reference { get; set; }
        public string produit_nom { get; set; }
        public string produit_libelle_court { get; set; }
        public string produit_libelle_long { get; set; }
        public string produit_rubrique { get; set; }
        public Nullable<int> produit_stock { get; set; }
        public string produit_photo { get; set; }
        public decimal prix_achat_initial { get; set; }
        public Nullable<decimal> prix_vente_ht { get; set; }
        public Nullable<double> taux_tva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fournit> Fournit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livrer> Livrer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sont_present> Sont_present { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rubrique> Rubrique { get; set; }
    }
}
